language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yenchenchou/docker-react:v1 -f Dockerfile.dev .

script:
  - docker run yenchenchou/docker-react:v1 npm run test -- --coverage